spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: none
  show-sql: true
  database-platform=org:
    hibernate:
      dialect: PostgreSQL10Dialect

spring.datasource:
  platform: postgres
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/Conference
  username: postgres
  password: postgres

spring:
  autoconfigure:
    exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    exclude[1]: org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

logging:
  level:
    root: INFO
    org.springframework.web: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: Confrerences
    description: spring boot application
    version: 1.0.0

